/**
 * Data access for the dashboard.
 *
 * Two modes:
 * - Full mode (local dev): hits the Next.js API routes, which shell out to
 *   the Python backend for real inference.
 * - Demo mode (static/hosted build, NEXT_PUBLIC_DEMO_MODE=1): loads
 *   precomputed JSON from /public/demo generated by
 *   scripts/export_demo_data.py, and runs the degradation simulation
 *   client-side. Used for the GitHub Pages deployment, where no Python
 *   backend exists. Every fetch also falls back to demo data if the API
 *   route fails, so the UI degrades gracefully.
 */

export const DEMO_MODE = process.env.NEXT_PUBLIC_DEMO_MODE === '1'

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || ''

async function getJson(url) {
  const res = await fetch(url)
  if (!res.ok) {
    let message = `Request failed (${res.status})`
    try {
      const body = await res.json()
      if (body?.error) message = body.error
    } catch { /* keep default message */ }
    throw new Error(message)
  }
  return res.json()
}

const demoData = (file) =>
  getJson(`${BASE_PATH}/demo/${file}`).catch(() => {
    throw new Error('Demo data unavailable for this selection')
  })

async function withDemoFallback(apiUrl, demoFile) {
  if (!DEMO_MODE) {
    try {
      return await getJson(apiUrl)
    } catch { /* fall through to demo data */ }
  }
  return demoData(demoFile)
}

export function fetchComparison() {
  return withDemoFallback('/api/comparison', 'comparison.json')
}

export function fetchEngines(dataset) {
  return withDemoFallback(`/api/engines?dataset=${dataset}`, `engines_${dataset}.json`)
}

export async function fetchPrediction(dataset, engine, model = 'ensemble') {
  const data = await withDemoFallback(
    `/api/predict?dataset=${dataset}&engine=${engine}&model=${model}`,
    `prediction_${dataset}_${engine}.json`,
  )
  // Demo snapshots are stored once per engine; project the selected model's
  // value out of individual_predictions so the model picker still works.
  if (data?.demo && model !== data.model && data.individual_predictions?.[model] != null) {
    const rul = data.individual_predictions[model]
    return {
      ...data,
      model,
      rul,
      error: Math.round((rul - data.true_rul) * 100) / 100,
      health_score: Math.max(0, Math.min(1, rul / 125)),
    }
  }
  return data
}

export function fetchTrajectory(dataset, engine) {
  return withDemoFallback(
    `/api/predict?action=trajectory&dataset=${dataset}&engine=${engine}`,
    `trajectory_${dataset}_${engine}.json`,
  )
}

export async function fetchSimulation(initialRul, degradationRate, faultMode) {
  if (!DEMO_MODE) {
    try {
      return await getJson(
        `/api/simulate?initial_rul=${initialRul}&rate=${degradationRate}&mode=${faultMode}`,
      )
    } catch { /* fall through to client-side simulation */ }
  }
  return simulateLocally(initialRul, degradationRate, faultMode)
}

/**
 * Client-side degradation simulation for demo mode. Mirrors the shape of the
 * Python DegradationSimulator output: monotonic RUL decay with fault-mode
 * dependent health curves and an AR(1)-correlated "model prediction" track.
 */
function simulateLocally(initialRul, degradationRate, faultMode) {
  // health decays faster late in life; exponent depends on the fault mode
  const healthExponent = { hpc: 1.4, fan: 1.15, combined: 1.7 }[faultMode] ?? 1.4
  const effectiveLife = Math.floor(initialRul / degradationRate)
  const trajectory = []
  let noise = 0

  for (let cycle = 1; cycle <= effectiveLife + 1; cycle++) {
    const trueRul = Math.max(0, Math.round(initialRul - cycle * degradationRate))
    const lifeFrac = Math.min(1, cycle / Math.max(1, effectiveLife))
    const health = Math.max(0, Math.pow(1 - lifeFrac, healthExponent))

    noise = 0.8 * noise + (Math.random() - 0.5) * 9
    const warmedUp = cycle >= 30
    trajectory.push({
      cycle,
      true_rul: trueRul,
      health_score: Math.round(health * 10000) / 10000,
      predicted_rul: Math.max(0, Math.round((trueRul + (warmedUp ? noise : noise * 2)) * 100) / 100),
      uncertainty: Math.round((4 + 6 * lifeFrac) * 100) / 100,
    })
    if (trueRul <= 0) break
  }

  return Promise.resolve({ trajectory, total_cycles: trajectory.length, demo: true })
}
